nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.3.0.cjs

enableScripts: false

packageExtensions:
  next-sitemap@*:
    dependencies:
      "@next/env": "13.0.5"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux
    - win32
